### ISSUE TITLE
Gradient between 2 colors or replace a gradient by another (City Map Task)

### ISSUE THREAD

**Issue by Elonex777** [ianfhunter/custom-asset-scripts-wonderdraft#23] opened 2018-11-10 20:51 UTC
Replace 2 colors values or a gradient by another, so without colors permutations. Might be useful for recolor top down basics building to use wonderdraft as a city mapmaking software.

Like taking watabou basic shapes building and recolors them and release as symbols set https://watabou.itch.io/medieval-fantasy-city-generator

Only if you find an easy way and it doesn't take you too much time

**Comment by ianfhunter** [comment] 2018-11-22 15:18
Looking at the svgs, doesnt seem to have a gradient. Going to close this as can't reproduce

**Closed by ianfhunter** 2018-11-22 15:18 UTC
Labels: feature-request
